struct Cell{v:u256,w:u256}

impl Cell {
    fn cached(mut self)->mut u256 {
        let mut tmp=self.v
        yield   mut tmp
        self.v=tmp
    }

    fn both(mut self)->(mut u256,ref u256) {
        (mut self.v,ref self.w)
    }

    fn present(mut self)->Option<mut u256> {
        match self.v {
            0 => yield Option::None,
            _ => yield Option::Some(mut self.v),
        }
    }
}

fn use_cell(cell:mut Cell)->u256 {
    let x=mut cell.v
    x+=1
    let (a,b)=cell.both()
    a+b
}
