msg FibMsg {
    #[selector = 0x01]
    Compute { n: u32 } -> u32,
}

struct FibStore {}

pub contract Fib {
    store: FibStore

    recv FibMsg {
        Compute { n } -> u32 {
            var a: u32 = 0
            var b: u32 = 1
            var i: u32 = 0
            while i < n {
                let next: u32 = a + b
                a = b
                b = next
                i = i + 1
            }
            return a
        }
    }
}
