use std::evm::{Create, Evm, RawOps, mem}

#[contract_init(Foo)]
fn init() uses (evm: mut Evm) {
    { // create child contract
        let len = evm.code_region_len(child_init)
        let offset = evm.code_region_offset(child_init)
        let dest = mem::alloc(len)
        evm.codecopy(dest: dest, offset: offset, len: len)
        evm.create2_raw(value: 0, offset: dest, len: len, salt: 0x1234)
    }

    let len = evm.code_region_len(runtime)
    let offset = evm.code_region_offset(runtime)
    let dest = mem::alloc(len)
    evm.codecopy(dest: dest, offset: offset, len: len)
    evm.return_data(offset: dest, len: len)
}

#[contract_runtime(Foo)]
fn runtime() uses (evm: mut Evm) {
    with (RawOps = evm) {
        match read_selector() {
            0x12345678 => { transfer() }
            0x23456789 => { balance() }
            _ => {}
        }
    }
    evm.return_data(offset: 0, len: 0)
}

#[contract_init(Child)]
fn child_init() uses (evm: mut Evm) {
    let len = evm.code_region_len(child_runtime)
    let offset = evm.code_region_offset(child_runtime)
    let dest = mem::alloc(len)
    evm.codecopy(dest: dest, offset: offset, len: len)
    evm.return_data(offset: dest, len: len)
}

#[contract_runtime(Child)]
fn child_runtime() uses (evm: mut Evm) {
    evm.calldatacopy(dest: 0, offset: 0, len: 4)
    evm.return_data(offset: 0, len: 4)
}

fn balance() uses (ops: RawOps) {
    ops.return_data(offset: 0, len: 0)
}

fn transfer() uses (ops: RawOps) {
    ops.return_data(offset: 0, len: 0)
}

pub fn read_selector() -> u256 uses (ops: RawOps) {
    let word = ops.calldataload(0)
    // Shift right by 224 bits to keep only the first four bytes.
    word >> 224
}
