use core::ptr
use std::evm::Evm

#[contract_init(Foo)]
fn init() uses (evm: mut Evm) {
    let len = evm.code_region_len(self::runtime)
    let offset = evm.code_region_offset(self::runtime)
    let dest = ptr::alloc_bytes(len)
    evm.codecopy(dest: dest, offset: offset, len: len)
    evm.return_data(offset: dest, len: len)
}

#[contract_runtime(Foo)]
fn runtime() uses (evm: mut Evm) {
    evm.return_data(offset: ptr::alloc_bytes(0), len: 0)
}
