use std::evm::{Evm, mem}

#[contract_init(Foo)]
fn init() uses (evm: mut Evm) {
    let len = evm.code_region_len(self::runtime)
    let offset = evm.code_region_offset(self::runtime)
    let dest = mem::alloc(len)
    evm.codecopy(dest: dest, offset: offset, len: len)
    evm.return_data(offset: dest, len: len)
}

#[contract_runtime(Foo)]
fn runtime() uses (evm: mut Evm) {
    evm.return_data(offset: 0, len: 0)
}
