use core::ptr
use std::evm::{MemPtr, RawMem, RawStorage, StorPtr}

struct Foo {
    a: u256,
    b: u256,
}

fn bump() uses (foo: mut Foo) {
    foo.a = foo.a + 1
    foo.b = foo.b + 2
}

fn test_effect_ptr_domains() uses (st: mut RawStorage, mem: mut RawMem) {
    let mp: MemPtr<Foo> = mem.mem_ptr(ptr::alloc<Foo>())
    with (mp) {
        bump()
    }

    let sp: StorPtr<Foo> = st.stor_ptr(0)
    with (sp) {
        bump()
    }

    let mut foo = Foo { a: 10, b: 20 }
    with (foo) {
        bump()
    }
}
