use core::{EffectHandle, ptr}
use std::evm::{MemPtr, RawMem}

struct Data {
    value: u256,
}

fn bump() uses (value: mut u256) {
    value += 1
}

fn raw_store() uses (data: mut MemPtr<Data>, mem: mut RawMem) {
    mem.mstore(addr: ptr::as_bytes(data.raw()), value: 8)
}

pub fn explicit_raw_boundaries() uses (mem: mut RawMem) {
    let value_ptr: MemPtr<u256> = mem.mem_ptr(ptr::alloc<u256>())
    with (value_ptr) {
        bump()
    }

    let data: MemPtr<Data> = mem.mem_ptr(ptr::alloc<Data>())
    with (data, mem) {
        raw_store()
    }
}
