use std::evm::{RawMem, RawOps, RawStorage}

pub fn load_word(ptr: u256) -> u256 uses (mem: RawMem) {
    mem.mload(ptr)
}

pub fn store_word(ptr: u256, value: u256) uses (mem: mut RawMem) {
    mem.mstore(addr: ptr, value: value)
}

pub fn store_byte(ptr: u256, value: u8) uses (mem: mut RawMem) {
    mem.mstore8(addr: ptr, value: value)
}

pub fn load_slot(slot: u256) -> u256 uses (sto: RawStorage) {
    sto.sload(slot)
}

pub fn store_slot(slot: u256, value: u256) uses (sto: mut RawStorage) {
    sto.sstore(slot: slot, value: value)
}

pub fn load_calldata(offset: u256) -> u256 uses (ops: RawOps) {
    ops.calldataload(offset)
}

pub fn finish(ptr: u256, len: u256) uses (ops: RawOps) {
    ops.return_data(offset: ptr, len: len)
}
