use core::ptr
use std::evm::{RawMem, RawOps, RawStorage}

pub fn load_word(ptr: *u8) -> u256 uses (mem: RawMem) {
    mem.mload(ptr)
}

pub fn store_word(ptr: *u8, value: u256) uses (mem: mut RawMem) {
    mem.mstore(addr: ptr, value: value)
}

pub fn store_byte(ptr: *u8, value: u8) uses (mem: mut RawMem) {
    mem.mstore8(addr: ptr, value: value)
}

pub fn load_slot(slot: u256) -> u256 uses (sto: RawStorage) {
    sto.sload(slot)
}

pub fn store_slot(slot: u256, value: u256) uses (sto: mut RawStorage) {
    sto.sstore(slot: slot, value: value)
}

pub fn load_calldata(offset: u256) -> u256 uses (ops: RawOps) {
    ops.calldataload(offset)
}

pub fn finish(data: *u8, len: u256) uses (ops: RawOps) {
    ops.return_data(data: ptr::MemBuffer::from_raw_parts(ptr: data, len: len))
}

pub fn main() -> u256
    uses (mem: mut RawMem, sto: mut RawStorage, ops: RawOps)
{
    let data = ptr::alloc_bytes(32)
    store_word(ptr: data, value: 1)
    store_byte(ptr: ptr::offset_bytes(data, 1), value: 2)
    store_slot(slot: 3, value: 4)
    load_word(ptr: data) + load_slot(slot: 3) + load_calldata(offset: 0)
}
