use std::evm::StorageMap

fn get_balance(addr: u256) -> u256
    uses (balances: StorageMap<u256, u256>)
{
    balances.get(key: addr)
}

fn set_balance(addr: u256, value: u256)
    uses (balances: mut StorageMap<u256, u256>)
{
    balances.set(key: addr, value)
}

pub fn main() -> u256 {
    let mut balances = StorageMap<u256, u256, 0>::new()
    with (balances) {
        set_balance(1, 2)
        get_balance(1)
    }
}

#[test]
fn foo() {
    let mut st = StorageMap<u256, u256, 0>::new()
    with (st) {
        main()
    }
}
