use std::evm::StoragePackedArray

msg Msg {
    #[selector = 0]
    Get -> u256,
}

fn get_status(_ id: u256) -> u256
    uses (status: StoragePackedArray<8>)
{
    status.get(id)
}

fn set_status(id: u256, value: u256)
    uses (status: mut StoragePackedArray<8>)
{
    status.set(i: id, value)
}

fn search_status(needle: u256, start: u256, end: u256) -> u256
    uses (status: StoragePackedArray<8>)
{
    let Option::Some(i) = status.search(needle: needle, start: start, end: end) else {
        core::panic()
    }
    i
}

contract C {
    mut status: StoragePackedArray<8>

    recv Msg {
        Get -> u256 uses (mut status) {
            with (mut status) {
                set_status(id: 1, value: 2)
                set_status(id: 33, value: 5)
            }
            with (status) {
                search_status(needle: 5, start: 0, end: 64)
                get_status(1)
            }
        }
    }
}
