use Maybe::*

extern {
    fn todo() -> !
}

trait Extract
where Self: * -> *
{
    fn extract<T>(self: own Self<T>) -> T
}

trait Clone {
    fn clone(self) -> Self
}

enum Maybe<T> {
    Just(T),
    Nothing
}
impl Extract for Maybe {
    fn extract<T>(self: own Self<T>) -> T {
        match self {
            Just(t) => t
            Nothing => todo()
        }
    }
}

struct S<T> {
    __priv: T
}
impl<T> S<T> {
    fn new(_ t: own T) -> Self {
        Self {
            __priv: t
        }
    }
}

pub fn extract<T, U>(_ t: own T<U>) -> U
where T: * -> * + Extract,
      U: Clone,
{
    t.extract()
}

impl Clone for bool {
    fn clone(self) -> bool {
        self
    }
}

fn foo() -> i32 {
    let s = S::new(false)
    extract(s)

    let opt = Just(1)
    extract(opt)
}
