use core::ops::{WrappingAdd, WrappingMul}

trait Marker {}

struct W {
    value: u256,
}

impl Marker for W {}

impl<T: Copy> WrappingMul for T {
    fn wrapping_mul(own self, _ other: own T) -> Self {
        self
    }
}

impl<T: Marker> WrappingAdd for T {
    fn wrapping_add(own self, _ other: own T) -> Self {
        self
    }
}

impl WrappingAdd for W {
    fn wrapping_add(own self, _ other: own W) -> W {
        self
    }
}
