trait CounterOps {
    fn value_ref(self) -> ref u256
    fn value_mut(self: mut Self) -> mut u256
}

struct Counter {
    value: u256,
}

impl CounterOps for Counter {
    fn value_ref(self) -> ref u256 {
        ref self.value
    }

    fn value_mut(self: mut Self) -> mut u256 {
        mut self.value
    }
}

fn use_receiver_modes() -> u256 {
    var counter = Counter { value: 1 }
    let value_ref = counter.value_ref()
    value_ref

    let value_mut = counter.value_mut()
    value_mut += 1
    counter.value
}
