#[error]
pub struct Panic {
    pub code: u256
}

impl Panic {
    pub fn from(_ code: u256) -> Self {
        Panic { code: code }
    }
}

pub use core::panics::{
    PANIC_GENERIC,
    PANIC_ASSERT,
    PANIC_OVERFLOW,
    PANIC_DIVISION_BY_ZERO,
    PANIC_ENUM_CONVERSION,
    PANIC_STORAGE_ENCODING,
    PANIC_POP_EMPTY,
    PANIC_INDEX_OUT_OF_BOUNDS,
    PANIC_OUT_OF_MEMORY,
    PANIC_ZERO_INIT_FUNCTION_POINTER,
}
