trait AbiSize {
    const ENCODED_SIZE: u256
}

trait Encode<A>: AbiSize {}

trait Contract {
    type InitArgs: Encode<u256>

    fn init_code_offset() -> u256
    fn init_code_len() -> u256
}

mod ops {
    extern {
        pub fn returndatasize() -> u256
        pub fn revert(offset: *u8, len: u256)
        pub fn codecopy(dest: *u8, offset: u256, len: u256)
    }
}

mod ptr {
    extern {
        pub fn alloc_bytes(_: u256) -> *u8
    }
}

fn create<C: Contract>() {
    let init_len = C::init_code_len()
    let init_off = C::init_code_offset()
    let args_len = C::InitArgs::ENCODED_SIZE
    let total_len = init_len + init_off

    let init_ptr = ptr::alloc_bytes(total_len)
    ops::codecopy(dest: init_ptr, offset: init_off, len: init_len)

    let ret_len = ops::returndatasize()
    let ret_ptr = ptr::alloc_bytes(ret_len)
    ops::revert(offset: ret_ptr, len: ret_len)
}
