extern {
    pub fn returndatasize() -> u256
    pub fn revert(offset: u256, len: u256)
}

mod ops {
    extern {
        pub fn returndatasize() -> u256
        pub fn revert(offset: u256, len: u256)
        pub fn alloc(_: u256) -> u256
    }
}

fn test() {
    let ret_len = ops::returndatasize()
    let ret_ptr = ops::alloc(ret_len)
    ops::revert(offset: ret_ptr, len: ret_len)
    returndatasize()
}
