pub fn factorial(var num: own u32) -> u32 {
    var res = 1
    while num > 0 {
        res *= num
        num -= 1
    }

    res
}

pub fn factorial2(var num: own u32) -> u32 {
    var res = 1
    while true {
        if num > 1 {
            res *= num
            num -= 1
        } else {
            return res
        }
    }
    
    return res
}


pub fn factorial3(var num: own u32) -> u32 {
    var res = 1
    while true {
        num = if num > 1 {
            res *= num
            num - 1
        } else {
            break
        }
    }
    
    res
}
