use std::evm::effects::assert

msg ContractMsg {
    #[selector = 0x01]
    Sum -> u256,
}

struct Store {
    sum: u256,
}

pub contract C {
    mut store: Store

    init(values: [u256; 4]) uses (mut store) {
        store.sum = values[0] + values[1] + values[2] + values[3]
    }

    recv ContractMsg {
        Sum -> u256 uses (store) {
            store.sum
        }
    }
}

#[test]
fn test_contract_init_fixed_array_arg() uses (evm: mut Evm) {
    let c = evm.create2<C>(value: 0, args: ([1, 2, 3, 4],), salt: 0)
    let sum: u256 = evm.call(addr: c, gas: 100000, value: 0, message: ContractMsg::Sum {})
    assert(sum == 10)
}
