use std::abi::DynArray
use std::evm::Log
use core::abi::store_word

#[event]
struct AddressList { values: DynArray<Address> }

#[test]
fn test_dyn_array_address_event() uses (log: mut Log) {
    assert!(
        AddressList::TOPIC0 == 0x561020ffe511e96c2b2544836b77735d4b65afe2bcc8ab164cbec96d16fa392c,
    )
    let ptr = core::ptr::alloc_bytes(64)
    unsafe { store_word(ptr: ptr, value: 1) }
    unsafe { store_word(ptr: core::ptr::offset_bytes(ptr, 32), value: 0x1234) }
    unsafe {
        log.emit(
            AddressList { values: DynArray::from_abi_tail(data: ptr, len: 1, size: 64) },
        )
    }
}
