use core::ops::WrappingSub

trait Marker {}

pub struct W {
    value: u256,
}

impl Copy for W {}
impl Marker for W {}

impl<T: Marker> WrappingSub for T {
    fn wrapping_sub(self, _ other: T) -> Self {
        self
    }
}

#[test]
fn local_bound_blanket_foreign_trait_impl_private_marker() {
    let a = W { value: 31 }
    let b = W { value: 11 }
    let c = a.wrapping_sub(b)

    assert(c.value == 31)
}
