use std::evm::{Evm, assert}

msg AbortMsg {
    #[selector = 0x01]
    GetBytes -> Bytes,
    #[selector = 0x02]
    GetScalar -> u256,
}

fn abort() -> ! {
    core::panic()
}

pub contract Aborter {
    recv AbortMsg {
        GetBytes -> Bytes {
            abort()
        }

        GetScalar -> u256 {
            abort()
        }
    }
}

#[test(should_revert)]
fn test_never_returning_recv_bytes()
uses (evm: mut Evm)
{
    let aborter = evm.create2<Aborter>(value: 0, args: (), salt: 0)
    assert(aborter.inner != 0)

    let returned: Bytes = evm.call(
        addr: aborter,
        gas: 1000000,
        value: 0,
        message: AbortMsg::GetBytes {},
    )
    assert(returned.len() == 0)
}

#[test(should_revert)]
fn test_never_returning_recv_scalar()
uses (evm: mut Evm)
{
    let aborter = evm.create2<Aborter>(value: 0, args: (), salt: 1)
    assert(aborter.inner != 0)

    let returned: u256 = evm.call(
        addr: aborter,
        gas: 1000000,
        value: 0,
        message: AbortMsg::GetScalar {},
    )
    assert(returned == 0)
}
