use std::evm::effects::assert
use core::ops::{SaturatingAdd, SaturatingMul, SaturatingSub}

#[test]
fn saturating_u8() {
    let max: u8 = 255
    let zero: u8 = 0
    assert(max.saturating_add(1) == max)
    assert(zero.saturating_sub(1) == zero)
    assert(max.saturating_mul(2) == max)
}

#[test]
fn saturating_u16() {
    let max: u16 = 65535
    let zero: u16 = 0
    assert(max.saturating_add(1) == max)
    assert(zero.saturating_sub(1) == zero)
    assert(max.saturating_mul(2) == max)
}

#[test]
fn saturating_u32() {
    let max: u32 = 4294967295
    let zero: u32 = 0
    assert(max.saturating_add(1) == max)
    assert(zero.saturating_sub(1) == zero)
    assert(max.saturating_mul(2) == max)
}

#[test]
fn saturating_u64() {
    let max: u64 = 18446744073709551615
    let zero: u64 = 0
    assert(max.saturating_add(1) == max)
    assert(zero.saturating_sub(1) == zero)
    assert(max.saturating_mul(2) == max)
}

#[test]
fn saturating_u128() {
    let max: u128 = 340282366920938463463374607431768211455
    let zero: u128 = 0
    assert(max.saturating_add(1) == max)
    assert(zero.saturating_sub(1) == zero)
    assert(max.saturating_mul(2) == max)
}

#[test]
fn saturating_u256() {
    let max: u256 = 115792089237316195423570985008687907853269984665640564039457584007913129639935
    let zero: u256 = 0
    assert(max.saturating_add(1) == max)
    assert(zero.saturating_sub(1) == zero)
    assert(max.saturating_mul(2) == max)
}

#[test]
fn saturating_usize() {
    let max: usize = 115792089237316195423570985008687907853269984665640564039457584007913129639935
    let zero: usize = 0
    assert(max.saturating_add(1) == max)
    assert(zero.saturating_sub(1) == zero)
    assert(max.saturating_mul(2) == max)
}

#[test]
fn saturating_i8() {
    let max: i8 = 127
    let min: i8 = -128
    assert(max.saturating_add(1) == max)
    assert(min.saturating_sub(1) == min)
    assert(max.saturating_mul(2) == max)
}

#[test]
fn saturating_i16() {
    let max: i16 = 32767
    let min: i16 = -32768
    assert(max.saturating_add(1) == max)
    assert(min.saturating_sub(1) == min)
    assert(max.saturating_mul(2) == max)
}

#[test]
fn saturating_i32() {
    let max: i32 = 2147483647
    let min: i32 = -2147483648
    assert(max.saturating_add(1) == max)
    assert(min.saturating_sub(1) == min)
    assert(max.saturating_mul(2) == max)
}

#[test]
fn saturating_i64() {
    let max: i64 = 9223372036854775807
    let min: i64 = -9223372036854775808
    assert(max.saturating_add(1) == max)
    assert(min.saturating_sub(1) == min)
    assert(max.saturating_mul(2) == max)
}

#[test]
fn saturating_i128() {
    let max: i128 = 170141183460469231731687303715884105727
    let min: i128 = -170141183460469231731687303715884105728
    assert(max.saturating_add(1) == max)
    assert(min.saturating_sub(1) == min)
    assert(max.saturating_mul(2) == max)
}

#[test]
fn saturating_i256() {
    let max: i256 = 57896044618658097711785492504343953926634992332820282019728792003956564819967
    let min: i256 = -57896044618658097711785492504343953926634992332820282019728792003956564819968
    assert(max.saturating_add(1) == max)
    assert(min.saturating_sub(1) == min)
    assert(max.saturating_mul(2) == max)
}

#[test]
fn saturating_isize() {
    let max: isize = 57896044618658097711785492504343953926634992332820282019728792003956564819967
    let min: isize = -57896044618658097711785492504343953926634992332820282019728792003956564819968
    assert(max.saturating_add(1) == max)
    assert(min.saturating_sub(1) == min)
    assert(max.saturating_mul(2) == max)
}
