pub struct Counter {
    pub value: u256,
}

fn inc() uses (counter: mut Counter) {
    counter.value = counter.value + 1
}

fn read() -> u256 uses (counter: Counter) {
    counter.value
}

#[test]
fn test_with_block_custom_effect() {
    let mut counter = Counter { value: 0 }

    let out: u256 = with (Counter = counter) {
        inc()
        read()
    }

    assert(out == 1)
}

#[test]
fn test_with_temp_block_custom_effect() {
    let out: u256 = with (Counter = Counter { value: 0 }) {
        inc()
        read()
    }

    assert(out == 1)
}
