use core::ptr
use std::evm::{Create, Evm}

#[contract_init(Parent)]
fn init() uses (evm: mut Evm) {
    let len = evm.code_region_len(runtime)
    let offset = evm.code_region_offset(runtime)
    let dest = ptr::alloc_bytes(len)
    evm.codecopy(dest: dest, offset: offset, len: len)
    evm.return_data(offset: dest, len: len)
}

#[contract_runtime(Parent)]
fn runtime() uses (evm: mut Evm) {
    let len = evm.code_region_len(child::child_init)
    let offset = evm.code_region_offset(child::child_init)
    let dest = ptr::alloc_bytes(len)
    evm.codecopy(dest: dest, offset: offset, len: len)
    let addr = evm.create2_raw(value: 0, offset: dest, len: len, salt: 0x1234)
    let data = ptr::alloc_bytes(32)
    evm.mstore(addr: data, value: addr.inner)
    evm.return_data(offset: data, len: 32)
}
