use std::evm::{Create, Evm, RawMem}

#[contract_init(Parent)]
fn init() uses (evm: mut Evm) {
    let len = evm.code_region_len(runtime)
    let offset = evm.code_region_offset(runtime)
    evm.codecopy(dest: 0, offset: offset, len: len)
    evm.return_data(offset: 0, len: len)
}

#[contract_runtime(Parent)]
fn runtime() uses (evm: mut Evm) {
    let len = evm.code_region_len(child::child_init)
    let offset = evm.code_region_offset(child::child_init)
    let dest = with (RawMem = evm) { allocate(bytes: len) }
    evm.codecopy(dest: dest, offset: offset, len: len)
    let addr = evm.create2_raw(value: 0, offset: dest, len: len, salt: 0x1234)
    evm.mstore(addr: 0, value: addr.inner)
    evm.return_data(offset: 0, len: 32)
}

fn allocate(bytes: u256) -> u256 uses (mem: mut RawMem) {
    let mut ptr = mem.mload(0x40)
    if ptr == 0 {
        ptr = 0x60
    }
    mem.mstore(addr: 0x40, value: ptr + bytes)
    ptr
}
