pub(crate) mod abi;
pub(crate) mod arg_selector;
pub mod body;
pub(crate) mod boundary;
pub(crate) mod call;
pub(crate) mod call_input;
pub(crate) mod classify;
mod consts;
pub(crate) mod conversion;
pub(crate) mod infer;
pub(crate) mod interface;
pub(crate) mod layout;
pub(crate) mod layout_evidence;
mod provider_space;
pub(crate) mod realize;
pub(crate) mod retention;
pub(crate) mod returns;
pub(crate) mod source;
pub(crate) mod tuple;
pub(crate) mod type_info;

pub use body::lower_to_rmir;
pub use call::collect_runtime_calls;
pub(crate) use consts::const_scalar_from_value;
