use core::abi::{Abi, AbiSize, Encode, store_word}
use std::abi::SolCompat
use std::evm::TopicValue

struct Bytes { word: u256 }

impl AbiSize for Bytes {
    const HEAD_SIZE: u256 = 32
    const IS_DYNAMIC: bool = false
}

impl<A: Abi> Encode<A> for Bytes {
    fn encode(own self, _ ptr: *u8) {
        store_word(ptr: ptr, value: self.word)
    }
}

impl SolCompat for Bytes {
    type S = String<7>
    const SOL_TYPE: Self::S = "uint256"
}

impl TopicValue for Bytes {
    fn as_topic(self) -> u256 {
        self.word
    }
}

#[event]
struct ShadowedDynamicName {
    #[indexed]
    value: Bytes,
}
