use core::functional::{Fn, Functor}

enum Result<E, T> {
    Err(E),
    Ok(T),
}

impl Functor for Result<()> {
    fn map<T, U, F: Fn<(T,), U>>(self: own Self<T>, _ f: F) -> Self<U> {
        match self {
            Result::Ok(t) => Result::Ok(f(t))
            Result::Err(e) => Result::Err(e)
        }
    }
}

fn f() {
    let r1 = Result<(), i32>::Ok(10)
    let r2 = r1.map(|value: own i32| -> bool { value > 0 })
    let _: Result<(), bool> = r2
}
