use std::evm::{StorageMap, StoragePackedArray, TSlot}

struct Store {
    balances: StorageMap<u256, u256>,
}

pub fn map_literal(_ store: mut Store) {
    store.balances = StorageMap { seed: 0 }
}

pub fn array_new_without_effect() -> StoragePackedArray<8, 0> {
    StoragePackedArray::new()
}

pub fn tslot_literal() -> TSlot<u256, 0> {
    TSlot {}
}

pub fn tslot_write_without_effect(slot: TSlot<u256, 0>) {
    slot.write(1)
}

pub fn readonly_store_set()
uses (store: Store)
{
    store.balances.set(key: 1, value: 2)
}
