use std::evm::StorageMap

msg LayoutMsg {
    #[selector = 1]
    Set { key: u256, value: u256 },
    #[selector = 2]
    Get { key: u256 } -> u256,
}

pub contract LayoutHoles {
    mut pair: (u256, u256)
    mut balances: StorageMap<u256, u256>
    mut tail: u256
    mut allowances: StorageMap<u256, u256>

    recv LayoutMsg {
        Set { key, value } uses (mut balances, mut allowances) {
            balances.set(key: key, value: value)
            allowances.set(key: key, value: value + 1)
        }

        Get { key } -> u256 uses (balances, allowances) {
            balances.get(key: key) + allowances.get(key: key)
        }
    }
}
