pub fn checked_add(v0: u8, v1: u8) -> u8 {
    v0 + v1
}

#[arithmetic(unchecked)]
pub fn unchecked_add(v0: u8, v1: u8) -> u8 {
    v0 + v1
}

#[arithmetic(unchecked)]
pub fn unchecked_div(v0: i8, v1: i8) -> i8 {
    v0 / v1
}

#[arithmetic(unchecked)]
pub fn unchecked_neg(v0: i8) -> i8 {
    -v0
}

#[arithmetic(unchecked)]
pub fn unchecked_pow_assign() -> u8 {
    let mut v0: u8 = 2
    v0 **= 8
    v0
}
