use core::effect_ref::{EffectHandle, EffectRef}

pub struct Storage<T> {
    value: T,
}

pub struct Ptr<T> {
    raw: u256,
}

impl EffectHandle for Ptr<Storage<u8>> {
    type Target = Storage<u8>
    type AddressSpace = core::effect_ref::Memory

    fn from_raw(raw: u256) -> Self { Self { raw } }
    fn raw(self) -> u256 { self.raw }
}

impl EffectRef<Storage<u8>> for Ptr<Storage<u8>> {}

pub fn needs() uses (store: Storage<u8>) {}

pub fn caller(x: own Ptr<Storage<u8>>) {
    with (Storage<u8> = x) {
        needs()
    }
}
