#[test(should_revert)]
fn test_const_oob_read_reverts() {
    let id = 10
    let arr: [u256; 2] = [10, 20]
    let val = arr[id]
}

#[test(should_revert)]
fn test_const_oob_write_reverts() {
    let id = 10
    var arr: [u256; 2] = [10, 20]
    arr[id] = 99
}

#[test(should_revert)]
fn test_const_oob_dead_read_reverts() {
    let id = 10
    let arr: [u256; 2] = [10, 20]
    let _val = arr[id]
}
